---

version: "3.7"

services:
  app:
    command: bash
    tty: true
    build: .
    environment:
      TZ: Asia/Tokyo
    links:
      - db
    ports:
      - 3000
    volumes:
      - ./:/usr/local/app/
  db:
    image: mysql:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
